### ISSUE TITLE
Support ext: news version 5.x.x?

### ISSUE THREAD

**Issue by typo3ua** [daCyberpunk/dated_news#1]
Hello!
Your extension will support the extension: "news" version 5.x.x?

**Comment by daCyberpunk** [comment]
Good question! I'm going to check this within the next days. Also it could be I'm doing some rework on it. 
Thank you for your interest.

**Comment by daCyberpunk** [comment]
The Extension does now support TYPO3 7.6 to 8.3 as well as tx_news 4.0.0 and higher! The new Version contains a lot of breaking changes. So try it out. Comments are welcome! :)

**Comment by typo3ua** [comment]
Hello!

After installing EXT: dated_news I get an error: `HTTP ERROR 500`

**Comment by daCyberpunk** [comment]
Thats really unspecific. Maybe you shoulkd clear your cache and check your logs.

**Comment by typo3ua** [comment]
I did it but nothing changed.
But when I deleted "dated_news" the error is disappears
