### ISSUE TITLE
eventstart in the selectbox "Sort by"

### ISSUE THREAD

**Issue by stephangrass** [daCyberpunk/dated_news#5]
To show eventstart in the selectbox "Sort by" of the news-plugin, the following line should be add to ext_tables.php.

$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['orderByNews'] .= ',eventstart';

Currently it's added in /Configuration/TCA/Overrides/tx_news_domain_model_news.php, but this is not working.

**Comment by daCyberpunk** [comment]
Fixed. Thanks!
