### ISSUE TITLE
Qtip.html is called from typo3ext/dated_news directory ONLY

### ISSUE THREAD

**Issue by agendartobias** [daCyberpunk/dated_news#8]
Hello, in Classes/Controller/NewsController.php (line 374) i see that the Qtip.html template is called from extension path. I need it to be configurable with TypoScript so i can call it from some local folder, because i need to change it.

Can you help me with that please!

**Comment by daCyberpunk** [comment]
That's really an issue, you're right. I'll fix that tomorrow, hopefully in the morning. Thanks for your report!

**Comment by daCyberpunk** [comment]
Please use the Github Master Version of dated_news. I fixed that there.

**Comment by agendartobias** [comment]
TNX!

**Comment by agendartobias** [comment]
But still i cannot call Resources/Private/Partials/Calendar/Qtip.html from some local folder, like other templates.

I see it is still ext path defined

        $qtip->setPartialRootPaths([
            'default' => ExtensionManagementUtility::extPath('dated_news').'Resources/Private/Partials',
        ]);

**Comment by daCyberpunk** [comment]
My friend, it was my failure. I thought you meant the javascript files. It was too early today morning. I'll take care later.

**Comment by agendartobias** [comment]
Okej, thank you!

**Comment by daCyberpunk** [comment]
Done.
